name: gerencia_net_plus_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

dependencies:
  args: ^2.3.0
  dio: ^5.3.0
  dio_http2_adapter: ^2.3.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.2

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  shelf_router_generator: ^1.0.6
